<template>
  <section>
    <div class="modal-card" style="width: auto">
      <header class="modal-card-head be-print-modal-head">
        <span class="be-modal-title">{{ $t("summaries") }}</span>
      </header>
      <section
        id="printBodySummaries"
        ref="PrintBody"
        class="be-modal-print-body"
      >
        <h1 class="subtitle is-3">{{ $t("title") }}</h1>
        <div v-html="$t('sole_proprietorship')"></div>
        <hr />
        <div v-html="$t('general_partnership')"></div>
        <hr />
        <div v-html="$t('limited_partnership')"></div>
        <hr />
        <div v-html="$t('limited_liability_partnership')"></div>
        <hr />
        <div v-html="$t('bc_corporation')"></div>
        <hr />
        <div v-html="$t('federal_corporation')"></div>
      </section>
      <footer class="modal-card-foot">
        <button class="button" type="button" @click="print()">
          {{ $t("print") }}
        </button>
        <button class="button" type="is-link">
          <a
            href="assets/EntityTypeLongDescriptionsFor-Profit.pdf"
            target="_blank"
          >
            {{ $t("download") }}
          </a>
        </button>
        <button class="button" type="button" @click="$parent.close()">
          {{ $t("close") }}
        </button>
      </footer>
    </div>
  </section>
</template>

<script>
import Vue from "vue";
import { Modal, Button } from "buefy";
import Printd from "printd";
import VueI18nSummaries from "vue-i18n";

Vue.use(VueI18nSummaries);
Vue.use(Modal);
Vue.use(Button);
// Create VueI18n instance with options
export const i18n = new VueI18nSummaries({
  locale: "en"
});

export default {
  i18n: {
    locale: "en",
    messages: {
      en: {
        summaries: "Summaries - Print View",
        print: "Print",
        download: "Download",
        close: "Close",
        title: "Entity Type Long Descriptions (For-Profit)",
        sole_proprietorship: `
          <h2 class="subtitle is-4">Sole Proprietorship</h2>
          <h3 class="subtitle be-subtitle-summaries is-5">What is it?</h3>
          <p>
            A sole proprietorship is the simplest form of a business, in which you and the company are considered a single entity. 
            As a sole proprietor, you do whatever is required for successful operation of your business. You make decisions, receive all profits, and claim all losses. 
            Although you may hire employees to assist you, you usually manage the business yourself.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How do I start one?</h3>
          <p>
            A proprietor does not have to register the business. The only legal requirement in establishing a sole proprietorship is to obtain licences which may be required 
            for certain types of business; for example, provincial and federal sales tax accounts, or municipal permits. If you plan to operate your sole proprietorship under 
            a business name other than your own, it’s best to register it with the province. You may also want to conduct a search of your proposed business name. If the name 
            you want to use is identical or similar to another business name, a search could help you avoid potential lawsuits.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What are the risks?</h3>
          <p>
            Your sole proprietorship is not legally separate from you, its owner. If you are a sole proprietor, you are personally responsible for all debts and obligations 
            related to your business.  A creditor with a claim against you would normally have a right against all of your assets, whether business or personal. Furthermore, 
            if a person should be harmed by your product or service, or while on your premises, you could be sued personally for damages. This is known as unlimited liability.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How will I be taxed?</h3>
          <p>
            If you are a sole proprietor, you pay personal income tax on the net income generated by your business. You’re required to report the business's financial details 
            in a separate section of the personal income tax form. If your business experiences a loss, you can deduct that loss from your other income.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What are the advantages of a sole proprietorship?</h3>
          <p>
            A sole proprietorship is simple and inexpensive to set up, in most cases free of regulatory and reporting requirements, and simple from a tax standpoint as it’s 
            part of your personal taxes. As the sole owner you have direct control over all decision making, all profits go to you, and you can claim business losses against 
            other sources of personal income.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What are the main disadvantages?</h3>
          <p>
            As a sole proprietor you have unlimited personal liability—you are personally responsible for the business’ financial and legal liabilities. There are fewer options 
            for raising capital; you will therefore need to rely solely on your personal resources and credit-worthiness. Profits will be taxed at the owner’s personal income 
            tax rate, which is typically higher than a corporate tax rate. And you cannot split income with family members through distribution of profits (dividends).
          </p>`,
        general_partnership: `
          <h2 class="subtitle is-4">General Partnership</h2>
          <h3 class="subtitle be-subtitle-summaries is-5">What is it?</h3>
          <p>
            In a general partnership you combine your resources with one or more others to make a profit. Each partner contributes money, property, or skills to the partnership. 
            The profits or losses are divided among the partners based on each partner’s share. Although partners are usually active in business operations, they may employ 
            others who are not partners to help run the business.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How do I start one?</h3>
          <p>
            A partnership is relatively easy to form. In fact, a simple oral agreement is enough. However, partners usually have a written agreement that outlines sharing of 
            revenues, expenses, how to split profits, and how to cover losses.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What about liabilities (risks)?</h3>
          <p>
            In a general partnership each partner is responsible for all liabilities of the partnership. This means that each partner is responsible for the actions of the 
            other partner(s), and has unlimited liability. 
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">Are partnerships regulated?</h3>
          <p>
            Although there are no formal filing requirements for general partnerships, they are governed by provincial legislation which sets out rules governing partner 
            obligations. 
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What else will I need to know?</h3>
          <p>
            Partnerships may have to obtain certain licences which may be required for certain types of business; for example, provincial and federal sales tax accounts, 
            or municipal permits. If you plan to operate your partnership under a business name other than the exact names of the partners, it’s best to conduct a search 
            of your proposed business name and register it with the province.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What are the advantages of a general partnership?</h3>
          <p>
            Although more time consuming and usually more expensive to set up than a sole proprietorship, a general partnership is easier and less expensive to set up and 
            run than a corporation. A general partnership also has a simpler tax structure—partners report income and expenses on their personal tax returns, in proportion 
            to their ownership stake. Because you report income on your personal return you have the opportunity to claim losses against other sources of income.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What are the main disadvantages?</h3>
          <p>
            In a general partnership, partners have unlimited personal liability: they are personally responsible for all of the business’ financial and legal liabilities. 
            It is more expensive to establish than a sole proprietorship if a partnership agreement is prepared. There are also fewer options for raising capital than a 
            corporation; the partnership will need to rely on partners’ personal resources and credit-worthiness. In a partnership all profits are taxed at the individual 
            partners’ personal income tax rate, which is typically higher than a corporate tax rate.
          </p>`,
        limited_partnership: `
          <h2 class="subtitle is-4">Limited Partnership</h2>
          <h3 class="subtitle be-subtitle-summaries is-5">What is it?</h3>
          <p>
            Limited partnerships are formed by two or more individuals or corporations. Each partner contributes money, property, or skills to the partnership. The profits 
            or losses are divided among the partners based on each partner’s share, with general partners usually earning a larger share. The partners may employ others who 
            are not partners.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How do I start one?</h3>
          <p>
            A limited partnership is more complex and expensive to set up than a general partnership. It requires a written agreement that outlines sharing of revenues, 
            expenses, how to split profits, and how to cover losses. You will need to consult a lawyer if you plan to form a limited partnership.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What about liabilities (risks)?</h3>
          <p>
            A limited partnership has legal status separate from its partners. There are two types of partner in a limited partnership—general and limited. The general partner 
            manages day to day operations, and has unlimited liability. The limited partners are typically investors without day-to-day management responsibilities. Their 
            financial and legal liability is limited to the amount invested. Limited partnerships usually have a finite life, and are often used in real estate development and 
            in the film industry.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How is the partnership taxed?</h3>
          <p>
            The partnership itself is not taxed. Instead, profits or losses flow through to the partners. When preparing their taxes, partners apply their ownership percentages 
            to income and expenses.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">Are limited partnerships regulated?</h3>
          <p>
            Limited partnerships are governed by provincial legislation which sets out rules governing partnership obligations in relation to third parties and between the 
            partners themselves. 
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What else will I need to know?</h3>
          <p>
            A "Partnership Declaration" must be filed to establish the Limited Partnership. You will also need to obtain certain licences which are required for your type 
            of business.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What are the advantages of a limited partnership?</h3>
          <p>
            The main advantage of a limited partnership over a general partnership is that the liability of limited partners is capped. And, unlike a general partnership, 
            limited partner ownership interests can be transferred, similar to shares in a corporation. Partners report income and expenses on their own tax returns. Because 
            partners report income on their own returns they have the opportunity to claim losses against other sources of income.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What are the main disadvantages?</h3>
          <p>
            The general partners in a limited partnership have unlimited personal liability: they are personally responsible for all of the business’ financial and legal 
            liabilities. Secondly, a limited partnership is more time consuming and expensive to set up than a general partnership, as a detailed partnership agreement is 
            required.
          </p>`,
        limited_liability_partnership: `
          <h2 class="subtitle is-4">Limited Liability Partnership</h2>
          <h3 class="subtitle be-subtitle-summaries is-5">What is it?</h3>
          <p>
            Limited liability partnerships (LLPs) are formed by two or more individuals or corporations. Each partner contributes money, property, or skills to the 
            partnership. The profits or losses are divided among the partners based on each partner's share. The partners may employ others who are not partners.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How do I start one?</h3>
          <p>
            An <abbr title="Limited Liability Partnership">LLP</abbr> is more complex and expensive to set up than a general partnership. It requires a written 
            agreement that outlines sharing of revenues, expenses, how to split profits, and how to cover losses. You will need to consult a lawyer if you plan 
            to form an <abbr title="Limited Liability Partnership">LLP</abbr>.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What about liabilities (risks)?</h3>
          <p>
            An <abbr title="Limited Liability Partnership">LLP</abbr> has legal status separate from its partners. There are two types of partner in a 
            <abbr title="Limited Liability Partnership">LLP</abbr>—<em>general</em> and <em>limited</em>. The general partner manages day to day operations, and has unlimited liability. 
            The limited partners are typically professionals like doctors, dentists, lawyers or accountants without day-to-day management responsibilities. Their financial 
            and legal liability is limited to the amount invested.
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How is the partnership taxed?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">Are <abbr title="Limited Liability Partnerships">LLPs</abbr> regulated?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What else will I need to know?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What are the advantages of a limited partnership?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What are the main disadvantages?</h3>
          <p>
          </p>`,
        bc_corporation: `
          <h2 class="subtitle is-4">BC Corporation</h2>
          <h3 class="subtitle be-subtitle-summaries is-5">What is it?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How do I start one?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What else will I need to do?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How can I raise money for the corporation?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How will shareholders get their money?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How long can a corporation exist?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What about liabilities?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What are the advantages of a corporation?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What are the main disadvantages?</h3>
          <p>
          </p>`,
        federal_corporation: `
          <h2 class="subtitle is-4">Federal Corporation</h2>
          <h3 class="subtitle be-subtitle-summaries is-5">What is it?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How do I start one?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What else will I need to do?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How can I raise money for the corporation?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How will shareholders get their money?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">How long can a corporation exist?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What about liabilities?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What are the advantages of a corporation?</h3>
          <p>
          </p>
          <h3 class="subtitle be-subtitle-summaries is-5">What are the main disadvantages?</h3>
          <p>
          </p>`
      },
      fr: {
        summaries: "Sommaires - Aperçu avant impression",
        print: "Imprimer",
        download: "Télécharger",
        close: "Fermer",
        title: "Entity Type Long Descriptions (For-Profit) FR",
        sole_proprietorship: `
          <h2 class="subtitle is-4">Sole Proprietorship FR</h2>
          `,
        general_partnership: `
          <h2 class="subtitle is-4">General Partnership FR</h2>
          `,
        limited_partnership: `
          <h2 class="subtitle is-4">Limited Partnership FR</h2>
          `,
        limited_liability_partnership: `
          <h2 class="subtitle is-4">Limited Liability Partnership FR</h2>
          `,
        bc_corporation: `
          <h2 class="subtitle is-4">BC Corporation FR</h2>
          `,
        federal_corporation: `
          <h2 class="subtitle is-4">Federal Corporation Fr</h2>
          `
      }
    }
  }, // end i18n
  props: ["lang"],
  mounted: function() {
    this.$i18n.locale = this.toggleLang;
  },
  computed: {
    toggleLang: function() {
      return this.lang;
    }
  }, // end computed
  methods: {
    print: function() {
      const d = new Printd();
      d.print(this.$refs.PrintBody);
    }
  } // end methods
};
</script>

<style scoped>
.subtitle .be-subtitle-summaries {
  color: #24465c;
  font-weight: 400;
}
</style>
